### ISSUE TITLE
add Logger to core package

### ISSUE THREAD

**Issue by mehedihasansjs** [aits-genesis/adk#1]
add a Logger service. Log can be turn on or off based on configuration. ie. in production I would like to turn the logging off. Or in anytime I should be able to turn on or off the logging.

- Apply color based on the log level. ie.
    - `debug` -> Yellow
    - `error` -> Red
    - `info` -> Teal

**Comment by nazmul-hasan54** [comment]
Hello vaiya! will this service define as a library or just service?

**Comment by mehedihasansjs** [comment]
@nazmul-hasan54 just a service under the core library

**Comment by mehedihasansjs** [comment]
@nazmul-hasan54 please do not create milestone. you can keep track on current milestone. you dont need to specify end date before completing the task. please insert completing date after completing it.

**Comment by nazmul-hasan54** [comment]
ok vaiya
    On Tuesday, May 7, 2024 at 12:24:06 AM GMT+6, Mehedi Hasan Likhon ***@***.***> wrote:  
 
 


Assigned #1 to @nazmul-hasan54.

**Comment by nazmul-hasan54** [comment]
Ok vaiya
    On Thursday, May 9, 2024 at 12:52:29 PM GMT+6, Mehedi Hasan Likhon ***@***.***> wrote:  
 
 


@nazmul-hasan54 please do not create milestone. you can keep track on current milestone. you dont need to specify end date before completing the task. please insert completing date after completing it.

**Comment by nazmul-hasan54** [comment]
Vaiya how to do this in anytime I should be able to turn console.log on or off? As per I know, dependency resolution modifiers like @Optional could be used to make a service on or off. Do you share any suggestion?
